import {
  SchoolProfile,
  SchoolClass,
  Subject,
  Student,
  Teacher,
  CBTExam,
  CBTAttempt,
  CAAndExamScore,
  StudentReportCard,
  CurriculumSubject,
  AttendanceRecord,
  TimetableSlot,
  Announcement,
  User,
  LessonNote,
  ResultPin,
} from './types';

export const initialSchoolProfile: SchoolProfile = {
  name: 'DIVINE ACADEMY SECONDARY SCHOOL',
  motto: 'Excellence and Godliness',
  address: 'Divine Academy Way, Okene, Kogi State, Nigeria',
  state: 'Kogi State',
  email: 'info@divineacademy.edu.ng',
  phone: '+234 803 123 4567',
  logoUrl: 'https://picsum.photos/seed/divine-academy-logo/200/200',
  currentSession: '2025/2026',
  currentTerm: '1st Term',
  principalName: 'Dr. A. O. Sule (Ph.D, M.Ed)',
  principalSignatureUrl: 'https://picsum.photos/seed/principal-sig/150/50',
};

export const initialUsers: User[] = [
  {
    id: 'user-admin-1',
    name: 'Dr. A. O. Sule',
    username: 'admin',
    email: 'admin@divineacademy.edu.ng',
    role: 'ADMIN',
    avatarUrl: 'https://picsum.photos/seed/admin-sule/100/100',
    phoneNumber: '+234 803 111 2222',
  },
  {
    id: 'user-teacher-1',
    name: 'Mr. Ibrahim Sule',
    username: 'ibrahim.sule',
    email: 'ibrahim.sule@divineacademy.edu.ng',
    role: 'TEACHER',
    teacherId: 'teacher-1',
    avatarUrl: 'https://picsum.photos/seed/teacher-ibrahim/100/100',
    phoneNumber: '+234 802 333 4444',
  },
  {
    id: 'user-student-1',
    name: 'Divine Johnson',
    username: 'divine.johnson',
    email: 'divine.johnson@student.divineacademy.edu.ng',
    role: 'STUDENT',
    studentId: 'student-1',
    avatarUrl: 'https://picsum.photos/seed/student-divine/100/100',
    phoneNumber: '+234 814 555 6666',
  },
  {
    id: 'user-parent-1',
    name: 'Chief Johnson',
    username: 'chief.johnson',
    email: 'johnson.parent@gmail.com',
    role: 'PARENT',
    studentId: 'student-1',
    phoneNumber: '+234 803 999 8888',
  },
];

export const initialClasses: SchoolClass[] = [
  { id: 'class-jss1a', name: 'JSS1 A', level: 'JSS1', arm: 'A', formTeacherId: 'teacher-1', studentCount: 32 },
  { id: 'class-jss1b', name: 'JSS1 B', level: 'JSS1', arm: 'B', formTeacherId: 'teacher-2', studentCount: 30 },
  { id: 'class-jss2a', name: 'JSS2 A', level: 'JSS2', arm: 'A', formTeacherId: 'teacher-3', studentCount: 28 },
  { id: 'class-jss3a', name: 'JSS3 A', level: 'JSS3', arm: 'A', formTeacherId: 'teacher-4', studentCount: 35 },
  { id: 'class-ss1sci', name: 'SS1 Science', level: 'SS1', arm: 'Science', formTeacherId: 'teacher-5', studentCount: 25 },
  { id: 'class-ss2sci', name: 'SS2 Science', level: 'SS2', arm: 'Science', formTeacherId: 'teacher-1', studentCount: 27 },
  { id: 'class-ss3sci', name: 'SS3 Science', level: 'SS3', arm: 'Science', formTeacherId: 'teacher-3', studentCount: 24 },
  { id: 'class-ss2art', name: 'SS2 Arts', level: 'SS2', arm: 'Arts', formTeacherId: 'teacher-6', studentCount: 22 },
];

export const initialSubjects: Subject[] = [
  // JSS 1 - 3 Subjects
  { id: 'sub-eng-jss', code: 'ENG101', name: 'English Studies', category: 'Core', levelGroup: 'JSS' },
  { id: 'sub-mth-jss', code: 'MTH101', name: 'Mathematics', category: 'Core', levelGroup: 'JSS' },
  { id: 'sub-nig-jss', code: 'NIG101', name: 'Nigerian Language', category: 'Arts', levelGroup: 'JSS' },
  { id: 'sub-isc-jss', code: 'ISC101', name: 'Intermediate Science', category: 'Science', levelGroup: 'JSS' },
  { id: 'sub-phe-jss', code: 'PHE101', name: 'Physical & Health Education', category: 'General', levelGroup: 'JSS' },
  { id: 'sub-dig-jss', code: 'DIG101', name: 'Digital Technologies', category: 'Science', levelGroup: 'JSS' },
  { id: 'sub-crs-jss', code: 'CRS101', name: 'CRS', category: 'Arts', levelGroup: 'JSS' },
  { id: 'sub-his-jss', code: 'HIS101', name: 'Nigerian History', category: 'Arts', levelGroup: 'JSS' },
  { id: 'sub-scs-jss', code: 'SCS101', name: 'Social & Citizenship Studies', category: 'Core', levelGroup: 'JSS' },
  { id: 'sub-cca-jss', code: 'CCA101', name: 'CCA', category: 'Arts', levelGroup: 'JSS' },
  { id: 'sub-bus-jss', code: 'BUS101', name: 'Business Studies', category: 'Commercial', levelGroup: 'JSS' },
  { id: 'sub-trd-jss', code: 'TRD101', name: 'Trade Subject', category: 'Commercial', levelGroup: 'JSS' },
  { id: 'sub-frn-jss', code: 'FRN101', name: 'French', category: 'Arts', levelGroup: 'JSS' },

  // SS 1 - 3 Subjects
  { id: 'sub-mth-ss', code: 'MTH201', name: 'General Mathematics', category: 'Core', levelGroup: 'SSS' },
  { id: 'sub-eng-ss', code: 'ENG201', name: 'English Language', category: 'Core', levelGroup: 'SSS' },
  { id: 'sub-chs-ss', code: 'CHS201', name: 'Citizenship and Heritage Studies', category: 'Core', levelGroup: 'SSS' },
  { id: 'sub-dig-ss', code: 'DIG201', name: 'Digital Technologies', category: 'Science', levelGroup: 'SSS' },
  { id: 'sub-bio-ss', code: 'BIO201', name: 'Biology', category: 'Science', levelGroup: 'SSS' },
  { id: 'sub-chm-ss', code: 'CHM201', name: 'Chemistry', category: 'Science', levelGroup: 'SSS' },
  { id: 'sub-phy-ss', code: 'PHY201', name: 'Physics', category: 'Science', levelGroup: 'SSS' },
  { id: 'sub-agr-ss', code: 'AGR201', name: 'Agriculture', category: 'General', levelGroup: 'SSS' },
  { id: 'sub-fmt-ss', code: 'FMT201', name: 'Further Mathematics', category: 'Science', levelGroup: 'SSS' },
  { id: 'sub-ped-ss', code: 'PED201', name: 'Physical Education', category: 'General', levelGroup: 'SSS' },
  { id: 'sub-hed-ss', code: 'HED201', name: 'Health Education', category: 'General', levelGroup: 'SSS' },
  { id: 'sub-fnt-ss', code: 'FNT201', name: 'Foods & Nutrition', category: 'Commercial', levelGroup: 'SSS' },
  { id: 'sub-geo-ss', code: 'GEO201', name: 'Geography', category: 'General', levelGroup: 'SSS' },
  { id: 'sub-his-ss', code: 'HIS201', name: 'Nigerian History', category: 'Arts', levelGroup: 'SSS' },
  { id: 'sub-gov-ss', code: 'GOV201', name: 'Government', category: 'Arts', levelGroup: 'SSS' },
  { id: 'sub-lit-ss', code: 'LIT201', name: 'Literature in English', category: 'Arts', levelGroup: 'SSS' },
  { id: 'sub-hmg-ss', code: 'HMG201', name: 'Home Management', category: 'Commercial', levelGroup: 'SSS' },
];

export const initialTeachers: Teacher[] = [
  {
    id: 'teacher-1',
    staffNo: 'DAT/2022/001',
    fullName: 'Mr. Ibrahim Sule',
    gender: 'Male',
    qualification: 'B.Sc. Ed. Mathematics (ABU Zaria)',
    email: 'ibrahim.sule@divineacademy.edu.ng',
    phone: '+234 802 333 4444',
    subjectsTaught: [
      { subjectId: 'sub-mth-jss', subjectName: 'Mathematics', classId: 'class-jss1a', className: 'JSS1 A' },
      { subjectId: 'sub-mth-ss', subjectName: 'General Mathematics', classId: 'class-ss2sci', className: 'SS2 Science' },
    ],
    isFormTeacherOf: 'JSS1 A',
    status: 'Active',
    joinedDate: '2022-09-01',
  },
  {
    id: 'teacher-2',
    staffNo: 'DAT/2022/002',
    fullName: 'Mrs. Fatima Bello',
    gender: 'Female',
    qualification: 'B.A. Ed. English Language (Unilorin)',
    email: 'fatima.bello@divineacademy.edu.ng',
    phone: '+234 803 444 5555',
    subjectsTaught: [
      { subjectId: 'sub-eng-jss', subjectName: 'English Studies', classId: 'class-jss1a', className: 'JSS1 A' },
      { subjectId: 'sub-eng-ss', subjectName: 'English Language', classId: 'class-jss2a', className: 'JSS2 A' },
    ],
    isFormTeacherOf: 'JSS1 B',
    status: 'Active',
    joinedDate: '2022-10-15',
  },
  {
    id: 'teacher-3',
    staffNo: 'DAT/2023/005',
    fullName: 'Engr. David Oche',
    gender: 'Male',
    qualification: 'B.Eng Electrical / PGDE (FUT Minna)',
    email: 'david.oche@divineacademy.edu.ng',
    phone: '+234 805 666 7777',
    subjectsTaught: [
      { subjectId: 'sub-phy-ss', subjectName: 'Physics', classId: 'class-ss2sci', className: 'SS2 Science' },
      { subjectId: 'sub-isc-jss', subjectName: 'Intermediate Science', classId: 'class-jss2a', className: 'JSS2 A' },
    ],
    isFormTeacherOf: 'JSS2 A',
    status: 'Active',
    joinedDate: '2023-01-10',
  },
  {
    id: 'teacher-4',
    staffNo: 'DAT/2023/008',
    fullName: 'Dr. Grace Yakubu',
    gender: 'Female',
    qualification: 'Ph.D Biochemistry (KSU Anyigba)',
    email: 'grace.yakubu@divineacademy.edu.ng',
    phone: '+234 807 888 9999',
    subjectsTaught: [
      { subjectId: 'sub-chm-ss', subjectName: 'Chemistry', classId: 'class-ss2sci', className: 'SS2 Science' },
      { subjectId: 'sub-bio-ss', subjectName: 'Biology', classId: 'class-ss3sci', className: 'SS3 Science' },
    ],
    isFormTeacherOf: 'JSS3 A',
    status: 'Active',
    joinedDate: '2023-09-01',
  },
];

export const initialStudents: Student[] = [
  {
    id: 'student-1',
    admissionNo: 'DA/2024/001',
    fullName: 'Divine Johnson',
    gender: 'Male',
    dateOfBirth: '2012-05-14',
    classId: 'class-jss1a',
    className: 'JSS1 A',
    guardianName: 'Chief Johnson',
    guardianPhone: '+234 803 999 8888',
    guardianEmail: 'johnson.parent@gmail.com',
    address: 'No. 12 GRA Road, Okene, Kogi State',
    passportUrl: 'https://picsum.photos/seed/student-divine/200/200',
    status: 'Active',
    enrolledDate: '2024-09-10',
  },
  {
    id: 'student-2',
    admissionNo: 'DA/2024/002',
    fullName: 'Fatima Usman',
    gender: 'Female',
    dateOfBirth: '2012-08-22',
    classId: 'class-jss1a',
    className: 'JSS1 A',
    guardianName: 'Alhaji Usman Bello',
    guardianPhone: '+234 802 777 6666',
    guardianEmail: 'usman.bello@gmail.com',
    address: 'Central Market Road, Okene, Kogi State',
    passportUrl: 'https://picsum.photos/seed/student-fatima/200/200',
    status: 'Active',
    enrolledDate: '2024-09-10',
  },
  {
    id: 'student-3',
    admissionNo: 'DA/2023/045',
    fullName: 'Emmanuel Adebayo',
    gender: 'Male',
    dateOfBirth: '2009-11-03',
    classId: 'class-ss2sci',
    className: 'SS2 Science',
    guardianName: 'Pastor Adebayo',
    guardianPhone: '+234 813 444 2222',
    guardianEmail: 'adebayo.pastor@yahoo.com',
    address: 'Old Secretariat Estate, Okene',
    passportUrl: 'https://picsum.photos/seed/student-emmanuel/200/200',
    status: 'Active',
    enrolledDate: '2023-09-05',
  },
  {
    id: 'student-4',
    admissionNo: 'DA/2023/050',
    fullName: 'Zainab Hassan',
    gender: 'Female',
    dateOfBirth: '2009-03-18',
    classId: 'class-ss2sci',
    className: 'SS2 Science',
    guardianName: 'Dr. Hassan Abdullahi',
    guardianPhone: '+234 806 111 3333',
    guardianEmail: 'dr.hassan@kogi.gov.ng',
    address: 'Lokoja Bypass, Okene',
    passportUrl: 'https://picsum.photos/seed/student-zainab/200/200',
    status: 'Active',
    enrolledDate: '2023-09-05',
  },
  {
    id: 'student-5',
    admissionNo: 'DA/2022/089',
    fullName: 'Chinedu Okafor',
    gender: 'Male',
    dateOfBirth: '2008-01-12',
    classId: 'class-ss3sci',
    className: 'SS3 Science',
    guardianName: 'Mr. Paul Okafor',
    guardianPhone: '+234 805 222 1111',
    guardianEmail: 'p.okafor@gmail.com',
    address: 'Ajaokuta Junction, Okene',
    passportUrl: 'https://picsum.photos/seed/student-chinedu/200/200',
    status: 'Active',
    enrolledDate: '2022-09-08',
  },
];

export const initialCBTExams: CBTExam[] = [
  {
    id: 'exam-jss1-mth-1',
    title: 'JSS1 Mathematics 1st Term Mid-Term CBT Test',
    subjectId: 'sub-mth-jss',
    subjectName: 'Mathematics',
    classId: 'class-jss1a',
    className: 'JSS1 A',
    teacherId: 'teacher-1',
    durationMinutes: 15,
    totalMarks: 5,
    passPercentage: 50,
    maxAttempts: 1,
    shuffleQuestions: true,
    status: 'Published',
    createdAt: '2025-10-12',
    questions: [
      {
        id: 'q1',
        questionText: 'Write the number 45,082 in words.',
        options: [
          { id: 'opt-a', text: 'Forty-five thousand and eighty-two' },
          { id: 'opt-b', text: 'Four hundred and fifty thousand eighty-two' },
          { id: 'opt-c', text: 'Forty-five thousand eight hundred and two' },
          { id: 'opt-d', text: 'Four thousand five hundred and eighty-two' },
        ],
        correctOptionId: 'opt-a',
        explanation: '45,082 = 45 Thousands + 0 Hundreds + 8 Tens + 2 Units = Forty-five thousand and eighty-two.',
        marks: 1,
        topic: 'Whole Numbers',
      },
      {
        id: 'q2',
        questionText: 'What is the place value of 7 in the number 3,745,210?',
        options: [
          { id: 'opt-a', text: 'Ten Thousands' },
          { id: 'opt-b', text: 'Hundred Thousands' },
          { id: 'opt-c', text: 'Millions' },
          { id: 'opt-d', text: 'Thousands' },
        ],
        correctOptionId: 'opt-b',
        explanation: 'In 3,745,210: 3 is Millions, 7 is Hundred Thousands, 4 is Ten Thousands.',
        marks: 1,
        topic: 'Place Value',
      },
      {
        id: 'q3',
        questionText: 'Find the Prime Factors of 36.',
        options: [
          { id: 'opt-a', text: '2 and 3' },
          { id: 'opt-b', text: '2, 3, and 6' },
          { id: 'opt-c', text: '1, 2, 3, 4, 6, 9' },
          { id: 'opt-d', text: '2 and 9' },
        ],
        correctOptionId: 'opt-a',
        explanation: 'Prime factors of 36 are 2 and 3 because 36 = 2^2 * 3^2, and 2, 3 are prime numbers.',
        marks: 1,
        topic: 'Factors and Multiples',
      },
      {
        id: 'q4',
        questionText: 'Convert 3/5 into a percentage.',
        options: [
          { id: 'opt-a', text: '35%' },
          { id: 'opt-b', text: '50%' },
          { id: 'opt-c', text: '60%' },
          { id: 'opt-d', text: '75%' },
        ],
        correctOptionId: 'opt-c',
        explanation: '(3 / 5) * 100% = 60%.',
        marks: 1,
        topic: 'Fractions and Percentages',
      },
      {
        id: 'q5',
        questionText: 'Simplify: 12 + (-5) - (-3).',
        options: [
          { id: 'opt-a', text: '4' },
          { id: 'opt-b', text: '10' },
          { id: 'opt-c', text: '14' },
          { id: 'opt-d', text: '20' },
        ],
        correctOptionId: 'opt-b',
        explanation: '12 - 5 + 3 = 7 + 3 = 10.',
        marks: 1,
        topic: 'Basic Algebra & Integers',
      },
    ],
  },
  {
    id: 'exam-ss2-phy-1',
    title: 'SS2 Physics Mid-Term CBT Test',
    subjectId: 'sub-phy-ss',
    subjectName: 'Physics',
    classId: 'class-ss2sci',
    className: 'SS2 Science',
    teacherId: 'teacher-3',
    durationMinutes: 20,
    totalMarks: 5,
    passPercentage: 50,
    maxAttempts: 1,
    shuffleQuestions: true,
    status: 'Published',
    createdAt: '2025-10-15',
    questions: [
      {
        id: 'pq1',
        questionText: 'Which of the following is a scalar quantity?',
        options: [
          { id: 'popt-a', text: 'Velocity' },
          { id: 'popt-b', text: 'Electric Potential' },
          { id: 'popt-c', text: 'Momentum' },
          { id: 'popt-d', text: 'Weight' },
        ],
        correctOptionId: 'popt-b',
        explanation: 'Electric potential has magnitude only and is scalar. Velocity, momentum, and weight have direction.',
        marks: 1,
        topic: 'Vectors & Scalars',
      },
      {
        id: 'pq2',
        questionText: 'A car accelerates uniformly from rest at 2 m/s² for 10 seconds. What is its final velocity?',
        options: [
          { id: 'popt-a', text: '10 m/s' },
          { id: 'popt-b', text: '15 m/s' },
          { id: 'popt-c', text: '20 m/s' },
          { id: 'popt-d', text: '100 m/s' },
        ],
        correctOptionId: 'popt-c',
        explanation: 'v = u + at = 0 + (2 * 10) = 20 m/s.',
        marks: 1,
        topic: 'Equations of Motion',
      },
      {
        id: 'pq3',
        questionText: 'What is the S.I. unit of Force?',
        options: [
          { id: 'popt-a', text: 'Joule (J)' },
          { id: 'popt-b', text: 'Watt (W)' },
          { id: 'popt-c', text: 'Newton (N)' },
          { id: 'popt-d', text: 'Pascal (Pa)' },
        ],
        correctOptionId: 'popt-c',
        explanation: 'Force is measured in Newtons (N = kg·m/s²).',
        marks: 1,
        topic: 'Units and Dimensions',
      },
      {
        id: 'pq4',
        questionText: 'A force of 50 N acts on a body of mass 10 kg. Calculate the acceleration.',
        options: [
          { id: 'popt-a', text: '0.2 m/s²' },
          { id: 'popt-b', text: '5 m/s²' },
          { id: 'popt-c', text: '50 m/s²' },
          { id: 'popt-d', text: '500 m/s²' },
        ],
        correctOptionId: 'popt-b',
        explanation: 'F = ma => a = F / m = 50 / 10 = 5 m/s².',
        marks: 1,
        topic: 'Newton Laws of Motion',
      },
      {
        id: 'pq5',
        questionText: 'Work done is defined as the product of force and distance in the direction of:',
        options: [
          { id: 'popt-a', text: 'Gravity' },
          { id: 'popt-b', text: 'Force' },
          { id: 'popt-c', text: 'Perpendicular axis' },
          { id: 'popt-d', text: 'Acceleration' },
        ],
        correctOptionId: 'popt-b',
        explanation: 'Work = Force x Displacement in the direction of the force.',
        marks: 1,
        topic: 'Work, Energy, and Power',
      },
    ],
  },
];

export const initialCBTAttempts: CBTAttempt[] = [
  {
    id: 'att-1',
    examId: 'exam-jss1-mth-1',
    examTitle: 'JSS1 Mathematics 1st Term Mid-Term CBT Test',
    studentId: 'student-1',
    studentName: 'Divine Johnson',
    admissionNo: 'DA/2024/001',
    answers: [
      { questionId: 'q1', selectedOptionId: 'opt-a', isCorrect: true, marksObtained: 4 },
      { questionId: 'q2', selectedOptionId: 'opt-b', isCorrect: true, marksObtained: 4 },
      { questionId: 'q3', selectedOptionId: 'opt-a', isCorrect: true, marksObtained: 4 },
      { questionId: 'q4', selectedOptionId: 'opt-c', isCorrect: true, marksObtained: 4 },
      { questionId: 'q5', selectedOptionId: 'opt-b', isCorrect: true, marksObtained: 4 },
    ],
    scoreObtained: 20,
    totalPossibleMarks: 20,
    percentageScore: 100,
    passed: true,
    startedAt: '2025-10-14 09:15',
    completedAt: '2025-10-14 09:23',
    timeTakenSeconds: 480,
  },
  {
    id: 'att-2',
    examId: 'exam-ss2-phy-1',
    examTitle: 'SS2 Physics Mid-Term CBT Test',
    studentId: 'student-3',
    studentName: 'Emmanuel Adebayo',
    admissionNo: 'DA/2023/045',
    answers: [
      { questionId: 'pq1', selectedOptionId: 'popt-b', isCorrect: true, marksObtained: 5 },
      { questionId: 'pq2', selectedOptionId: 'popt-c', isCorrect: true, marksObtained: 5 },
      { questionId: 'pq3', selectedOptionId: 'popt-c', isCorrect: true, marksObtained: 5 },
      { questionId: 'pq4', selectedOptionId: 'popt-b', isCorrect: true, marksObtained: 5 },
      { questionId: 'pq5', selectedOptionId: 'popt-a', isCorrect: false, marksObtained: 0 },
    ],
    scoreObtained: 20,
    totalPossibleMarks: 25,
    percentageScore: 80,
    passed: true,
    startedAt: '2025-10-16 11:00',
    completedAt: '2025-10-16 11:14',
    timeTakenSeconds: 840,
  },
];

export const initialScores: CAAndExamScore[] = [
  // Divine Johnson - JSS1 A
  {
    id: 'sc-1',
    studentId: 'student-1',
    studentName: 'Divine Johnson',
    admissionNo: 'DA/2024/001',
    classId: 'class-jss1a',
    className: 'JSS1 A',
    subjectId: 'sub-mth',
    subjectName: 'Mathematics',
    session: '2025/2026',
    term: '1st Term',
    ca1: 14,
    ca2: 13,
    examScore: 62,
    totalScore: 89,
    grade: 'A',
    remark: 'Distinction',
    positionInClass: 1,
  },
  {
    id: 'sc-2',
    studentId: 'student-1',
    studentName: 'Divine Johnson',
    admissionNo: 'DA/2024/001',
    classId: 'class-jss1a',
    className: 'JSS1 A',
    subjectId: 'sub-eng',
    subjectName: 'English Language',
    session: '2025/2026',
    term: '1st Term',
    ca1: 13,
    ca2: 12,
    examScore: 58,
    totalScore: 83,
    grade: 'A',
    remark: 'Distinction',
    positionInClass: 2,
  },
  {
    id: 'sc-3',
    studentId: 'student-1',
    studentName: 'Divine Johnson',
    admissionNo: 'DA/2024/001',
    classId: 'class-jss1a',
    className: 'JSS1 A',
    subjectId: 'sub-bst',
    subjectName: 'Basic Science & Tech',
    session: '2025/2026',
    term: '1st Term',
    ca1: 12,
    ca2: 14,
    examScore: 54,
    totalScore: 80,
    grade: 'A',
    remark: 'Distinction',
    positionInClass: 1,
  },
  {
    id: 'sc-4',
    studentId: 'student-1',
    studentName: 'Divine Johnson',
    admissionNo: 'DA/2024/001',
    classId: 'class-jss1a',
    className: 'JSS1 A',
    subjectId: 'sub-agr',
    subjectName: 'Agricultural Science',
    session: '2025/2026',
    term: '1st Term',
    ca1: 11,
    ca2: 13,
    examScore: 52,
    totalScore: 76,
    grade: 'A',
    remark: 'Distinction',
    positionInClass: 3,
  },
  {
    id: 'sc-5',
    studentId: 'student-1',
    studentName: 'Divine Johnson',
    admissionNo: 'DA/2024/001',
    classId: 'class-jss1a',
    className: 'JSS1 A',
    subjectId: 'sub-civ',
    subjectName: 'Civic Education',
    session: '2025/2026',
    term: '1st Term',
    ca1: 14,
    ca2: 14,
    examScore: 60,
    totalScore: 88,
    grade: 'A',
    remark: 'Distinction',
    positionInClass: 1,
  },

  // Fatima Usman - JSS1 A
  {
    id: 'sc-6',
    studentId: 'student-2',
    studentName: 'Fatima Usman',
    admissionNo: 'DA/2024/002',
    classId: 'class-jss1a',
    className: 'JSS1 A',
    subjectId: 'sub-mth',
    subjectName: 'Mathematics',
    session: '2025/2026',
    term: '1st Term',
    ca1: 11,
    ca2: 12,
    examScore: 50,
    totalScore: 73,
    grade: 'A',
    remark: 'Excellent',
    positionInClass: 4,
  },
  {
    id: 'sc-7',
    studentId: 'student-2',
    studentName: 'Fatima Usman',
    admissionNo: 'DA/2024/002',
    classId: 'class-jss1a',
    className: 'JSS1 A',
    subjectId: 'sub-eng',
    subjectName: 'English Language',
    session: '2025/2026',
    term: '1st Term',
    ca1: 14,
    ca2: 14,
    examScore: 60,
    totalScore: 88,
    grade: 'A',
    remark: 'Distinction',
    positionInClass: 1,
  },

  // Emmanuel Adebayo - SS2 Science
  {
    id: 'sc-8',
    studentId: 'student-3',
    studentName: 'Emmanuel Adebayo',
    admissionNo: 'DA/2023/045',
    classId: 'class-ss2sci',
    className: 'SS2 Science',
    subjectId: 'sub-mth',
    subjectName: 'Mathematics',
    session: '2025/2026',
    term: '1st Term',
    ca1: 13,
    ca2: 14,
    examScore: 58,
    totalScore: 85,
    grade: 'A',
    remark: 'Distinction',
    positionInClass: 2,
  },
  {
    id: 'sc-9',
    studentId: 'student-3',
    studentName: 'Emmanuel Adebayo',
    admissionNo: 'DA/2023/045',
    classId: 'class-ss2sci',
    className: 'SS2 Science',
    subjectId: 'sub-phy',
    subjectName: 'Physics',
    session: '2025/2026',
    term: '1st Term',
    ca1: 14,
    ca2: 15,
    examScore: 61,
    totalScore: 90,
    grade: 'A',
    remark: 'Distinction',
    positionInClass: 1,
  },
  {
    id: 'sc-10',
    studentId: 'student-3',
    studentName: 'Emmanuel Adebayo',
    admissionNo: 'DA/2023/045',
    classId: 'class-ss2sci',
    className: 'SS2 Science',
    subjectId: 'sub-chm',
    subjectName: 'Chemistry',
    session: '2025/2026',
    term: '1st Term',
    ca1: 12,
    ca2: 13,
    examScore: 55,
    totalScore: 80,
    grade: 'A',
    remark: 'Distinction',
    positionInClass: 2,
  },
];

export const initialReportCards: StudentReportCard[] = [
  {
    id: 'rc-divine-1st-term',
    studentId: 'student-1',
    studentName: 'Divine Johnson',
    admissionNo: 'DA/2024/001',
    classId: 'class-jss1a',
    className: 'JSS1 A',
    session: '2025/2026',
    term: '1st Term',
    academicScores: initialScores.filter((s) => s.studentId === 'student-1'),
    totalScoreSum: 416,
    averageScore: 83.2,
    positionInClass: 1,
    classSize: 32,
    affectiveDomain: {
      punctuality: 5,
      neatness: 5,
      politeness: 5,
      honesty: 5,
      leadership: 4,
      cooperation: 5,
      attentiveness: 5,
    },
    psychomotorDomain: {
      handwriting: 4,
      sportsAndGames: 5,
      verbalFluency: 5,
      handlingTools: 4,
      craftsAndArts: 4,
    },
    teacherComment: 'Divine is an exceptionally brilliant and hardworking student. He leads the class with exemplary character.',
    principalComment: 'A stellar result! Keep maintaining this commendable level of excellence.',
    nextTermBegins: '2026-01-12',
    status: 'Published',
  },
  {
    id: 'rc-emmanuel-1st-term',
    studentId: 'student-3',
    studentName: 'Emmanuel Adebayo',
    admissionNo: 'DA/2023/045',
    classId: 'class-ss2sci',
    className: 'SS2 Science',
    session: '2025/2026',
    term: '1st Term',
    academicScores: initialScores.filter((s) => s.studentId === 'student-3'),
    totalScoreSum: 255,
    averageScore: 85.0,
    positionInClass: 1,
    classSize: 27,
    affectiveDomain: {
      punctuality: 5,
      neatness: 4,
      politeness: 5,
      honesty: 5,
      leadership: 5,
      cooperation: 4,
      attentiveness: 5,
    },
    psychomotorDomain: {
      handwriting: 4,
      sportsAndGames: 4,
      verbalFluency: 5,
      handlingTools: 5,
      craftsAndArts: 3,
    },
    teacherComment: 'Emmanuel displays profound analytical skills in Physics and Mathematics. Highly commendable.',
    principalComment: 'Outstanding performance. Divine Academy is proud of your academic devotion.',
    nextTermBegins: '2026-01-12',
    status: 'Published',
  },
];

// Rich Sample Curriculum Database (JSS1 to SS3)
export const initialCurriculum: CurriculumSubject[] = [
  {
    id: 'cur-jss1-mth-term1',
    level: 'JSS1',
    subjectName: 'Mathematics',
    term: '1st Term',
    weeks: [
      {
        weekNumber: 1,
        topic: 'Whole Numbers: Count & Write in Millions/Billions',
        subTopics: ['Definition of Whole Numbers', 'Place Value System', 'Reading and Writing Numbers in Words and Figures'],
        objectives: [
          'State the place value of any given digit in whole numbers up to billions.',
          'Read and write numbers in words and figures accurately.',
          'Solve real-life problems involving whole numbers.',
        ],
        instructionalMaterials: ['Place Value Charts', 'Abacus', 'Flash Cards', 'Chalkboard'],
        previousKnowledge: 'Learners have learned basic counting up to 100,000 in Primary School.',
        teacherActivities: 'Teacher demonstrates place value system on the board using a 10-column table (Units to Billions). Guides students to read numbers aloud.',
        learnerActivities: 'Learners form groups to read number cards and write equivalent values on their exercise books.',
        boardSummary: 'Whole Numbers start from 0, 1, 2, 3...\nPlace Value Order: Units, Tens, Hundreds, Thousands, Ten-Thousands, Hundred-Thousands, Millions, Ten-Millions, Hundred-Millions, Billions.',
        evaluationQuestions: [
          'What is the place value of 9 in 89,451,200?',
          'Write six hundred and four million, twelve thousand and seven in figures.',
        ],
        homework: 'Complete Exercise 1A, Questions 1-10 in New General Mathematics JSS1, Page 8.',
      },
      {
        weekNumber: 2,
        topic: 'Prime Factors, HCF & LCM',
        subTopics: ['Prime Numbers vs Composite Numbers', 'Expressing Numbers as Product of Prime Factors', 'Highest Common Factor (HCF)', 'Least Common Multiple (LCM)'],
        objectives: [
          'Identify prime numbers between 1 and 100.',
          'Express whole numbers as products of prime factors in index form.',
          'Calculate HCF and LCM of two or three numbers.',
        ],
        instructionalMaterials: ['Prime Number Grid', 'Factor Trees Diagrams', 'Multiplication Tables'],
        previousKnowledge: 'Learners understand basic multiplication tables.',
        teacherActivities: 'Teacher introduces the Sieve of Eratosthenes to identify prime numbers. Illustrates prime factor division trees on board.',
        learnerActivities: 'Learners construct factor trees for numbers 24, 36, and 48.',
        boardSummary: 'Prime Numbers have exactly two factors: 1 and itself (2, 3, 5, 7, 11...).\nHCF: Product of common prime factors with lowest powers.\nLCM: Product of all prime factors with highest powers.',
        evaluationQuestions: ['Find the HCF of 18 and 24.', 'Calculate the LCM of 12, 16, and 20.'],
        homework: 'Exercise 2B, Questions 1-5.',
      },
      {
        weekNumber: 3,
        topic: 'Fractions: Equivalent, Addition & Subtraction',
        subTopics: ['Types of Fractions (Proper, Improper, Mixed)', 'Equivalent Fractions', 'Ordering Fractions', 'Addition and Subtraction of Fractions'],
        objectives: ['Differentiate between types of fractions.', 'Find equivalent fractions.', 'Add and subtract proper and mixed fractions.'],
        instructionalMaterials: ['Fraction Strips', 'Fraction Circles', 'Chalkboard'],
        previousKnowledge: 'Learners know basic fractions like half and quarter.',
        teacherActivities: 'Teacher cuts paper circles to show 1/2 = 2/4 = 4/8. Explains finding LCM of denominators.',
        learnerActivities: 'Learners fold paper strips to compare fractions.',
        boardSummary: 'Equivalent Fractions: Multiply/Divide numerator and denominator by same non-zero number.\nTo add/subtract fractions with different denominators, find LCM of denominators.',
        evaluationQuestions: ['Simplify 3/4 + 2/5.', 'Evaluate 5 1/3 - 2 3/4.'],
        homework: 'Exercise 3C, Page 22.',
      },
    ],
  },
  {
    id: 'cur-jss1-bst-term1',
    level: 'JSS1',
    subjectName: 'Basic Science & Tech',
    term: '1st Term',
    weeks: [
      {
        weekNumber: 1,
        topic: 'Living Things and Non-Living Things',
        subTopics: ['Definition of Matter', 'Characteristics of Living Things (MR NIGER D)', 'Differences between Plants and Animals'],
        objectives: [
          'Define living and non-living things with local examples.',
          'List and explain the 8 characteristics of living things.',
          'Compare plants and animals.',
        ],
        instructionalMaterials: ['Potted Plant', 'Live Earthworm/Insect', 'Rocks/Stones', 'Wall Chart'],
        previousKnowledge: 'Learners observe plants and animals in their home environment.',
        teacherActivities: 'Teacher brings a live plant and a stone to class. Asks students to observe movement and response to stimulus.',
        learnerActivities: 'Learners list 5 living things and 5 non-living things found in the Divine Academy compound.',
        boardSummary: 'MR NIGER D:\nMovement, Respiration, Nutrition, Irritability, Growth, Excretion, Reproduction, Death.',
        evaluationQuestions: ['State 5 differences between a mango tree and a goat.', 'Why is a motor car non-living despite moving?'],
        homework: 'Collect 3 different leaves and press them in your workbook.',
      },
    ],
  },
  {
    id: 'cur-ss2-phy-term1',
    level: 'SS2',
    subjectName: 'Physics',
    term: '1st Term',
    weeks: [
      {
        weekNumber: 1,
        topic: 'Position, Distance and Displacement',
        subTopics: ['Concept of Position in Space', 'Distance vs Displacement', 'Rectangular Coordinate System (x, y, z)'],
        objectives: [
          'Distinguish clearly between scalar distance and vector displacement.',
          'Represent position using coordinate system.',
          'Solve numerical problems on displacement vector sums.',
        ],
        instructionalMaterials: ['Meter Rule', 'Measuring Tape', 'Graph Paper', 'Rays & Vectors Model'],
        previousKnowledge: 'Learners covered fundamental units and vectors in SS1 Physics.',
        teacherActivities: 'Teacher walks 4 meters East, then 3 meters North on the laboratory floor, pointing out total distance (7m) vs displacement magnitude (5m at N53°E).',
        learnerActivities: 'Learners plot displacement vectors on graph paper using scale 1cm = 1m.',
        boardSummary: 'Distance = Total ground covered (Scalar, Magnitude only).\nDisplacement = Shortest straight line from start to finish with direction (Vector).\nMagnitude s = √(x² + y²).',
        evaluationQuestions: [
          'A student walks 6 km West and then 8 km North. Find his total distance and displacement.',
          'State two differences between distance and displacement.',
        ],
        homework: 'Physics for Senior Secondary Schools Book 2, Page 14, Q1-Q6.',
      },
    ],
  },
];

export const initialAttendanceRecords: AttendanceRecord[] = [
  { id: 'att-rec-1', date: '2026-08-17', classId: 'class-jss1a', className: 'JSS1 A', studentId: 'student-1', studentName: 'Divine Johnson', status: 'Present' },
  { id: 'att-rec-2', date: '2026-08-17', classId: 'class-jss1a', className: 'JSS1 A', studentId: 'student-2', studentName: 'Fatima Usman', status: 'Present' },
  { id: 'att-rec-3', date: '2026-08-17', classId: 'class-ss2sci', className: 'SS2 Science', studentId: 'student-3', studentName: 'Emmanuel Adebayo', status: 'Present' },
  { id: 'att-rec-4', date: '2026-08-17', classId: 'class-ss2sci', className: 'SS2 Science', studentId: 'student-4', studentName: 'Zainab Hassan', status: 'Late', remark: 'Arrived at 08:25 AM due to rain' },
];

export const initialTimetable: TimetableSlot[] = [
  // JSS1 A
  { id: 'tt-1', classId: 'class-jss1a', day: 'Monday', periodNumber: 1, timeRange: '08:00 - 08:40 AM', subjectName: 'Mathematics', teacherName: 'Mr. Ibrahim Sule' },
  { id: 'tt-2', classId: 'class-jss1a', day: 'Monday', periodNumber: 2, timeRange: '08:40 - 09:20 AM', subjectName: 'English Language', teacherName: 'Mrs. Fatima Bello' },
  { id: 'tt-3', classId: 'class-jss1a', day: 'Monday', periodNumber: 3, timeRange: '09:20 - 10:00 AM', subjectName: 'Basic Science & Tech', teacherName: 'Engr. David Oche' },
  { id: 'tt-4', classId: 'class-jss1a', day: 'Tuesday', periodNumber: 1, timeRange: '08:00 - 08:40 AM', subjectName: 'Civic Education', teacherName: 'Mrs. Aisha Garba' },
  { id: 'tt-5', classId: 'class-jss1a', day: 'Wednesday', periodNumber: 2, timeRange: '08:40 - 09:20 AM', subjectName: 'Agricultural Science', teacherName: 'Mr. Okoro Chinedu' },

  // SS2 Science
  { id: 'tt-6', classId: 'class-ss2sci', day: 'Monday', periodNumber: 1, timeRange: '08:00 - 08:40 AM', subjectName: 'Physics', teacherName: 'Engr. David Oche' },
  { id: 'tt-7', classId: 'class-ss2sci', day: 'Monday', periodNumber: 2, timeRange: '08:40 - 09:20 AM', subjectName: 'Chemistry', teacherName: 'Dr. Grace Yakubu' },
  { id: 'tt-8', classId: 'class-ss2sci', day: 'Monday', periodNumber: 3, timeRange: '09:20 - 10:00 AM', subjectName: 'Mathematics', teacherName: 'Mr. Ibrahim Sule' },
];

export const initialAnnouncements: Announcement[] = [
  {
    id: 'anc-1',
    title: 'Mid-Term CBT Examination Schedule Released',
    content: 'All students and subject teachers are hereby notified that the 1st Term Mid-Term Computer-Based Tests (CBT) will commence next week Monday. Ensure your student portal login credentials are valid.',
    category: 'Exam',
    targetRole: 'ALL',
    author: 'Vice Principal (Academics)',
    createdAt: '2025-10-10',
  },
  {
    id: 'anc-2',
    title: 'Parent-Teacher Association (PTA) Meeting',
    content: 'Notice is hereby given for the 1st Term General PTA Meeting scheduled for Saturday at 10:00 AM in the Divine Academy School Auditorium, Okene. Attendance is compulsory for all guardians.',
    category: 'PTA',
    targetRole: 'PARENT',
    author: 'School Management',
    createdAt: '2025-10-12',
  },
  {
    id: 'anc-3',
    title: 'Curriculum & Lesson Plan Review Deadline',
    content: 'All subject teachers must submit their Weeks 1-13 lesson plans and CBT question bank uploads to the Curriculum Centre on or before Friday 4:00 PM.',
    category: 'Academic',
    targetRole: 'TEACHER',
    author: 'Principal Office',
    createdAt: '2025-10-08',
  },
];

export const initialLessonNotes: LessonNote[] = [
  {
    id: 'note-1',
    classId: 'class-jss1a',
    className: 'JSS1 A',
    subjectId: 'sub-mth-jss',
    subjectName: 'Mathematics',
    title: 'Whole Numbers & Place Value Concept',
    weekNumber: 1,
    term: '1st Term',
    content: 'Comprehensive lecture notes on counting, writing, and identifying place value of digits up to millions. Includes worked examples and class exercises.',
    uploadedBy: 'Mr. Ibrahim Sule',
    uploadedAt: '2025-09-05',
  },
  {
    id: 'note-2',
    classId: 'class-ss2sci',
    className: 'SS2 Science',
    subjectId: 'sub-mth-jss',
    subjectName: 'Mathematics',
    title: 'Quadratic Equations & Graphical Solutions',
    weekNumber: 2,
    term: '1st Term',
    content: 'Detailed explanation of solving quadratic equations by factorization, completing the square, and graphical methods with parabola plots.',
    uploadedBy: 'Mr. Ibrahim Sule',
    uploadedAt: '2025-09-12',
  },
];

export const initialResultPins: ResultPin[] = [
  { id: 'pin-1', pin: 'DIV-2025-847291', serialNumber: 'SN-001', isUsed: false },
  { id: 'pin-2', pin: 'DIV-2025-392810', serialNumber: 'SN-002', isUsed: false },
  { id: 'pin-3', pin: 'DIV-2025-502938', serialNumber: 'SN-003', isUsed: false },
  { id: 'pin-4', pin: 'DIV-2025-109283', serialNumber: 'SN-004', isUsed: true, usedByStudentName: 'Divine Johnson', usedAt: '2025-08-15' },
];
